### ISSUE TITLE
Cannot continue. The application is improperly formatted. (addedToolbar branch)

### ISSUE THREAD

**Issue by MysteryFlask** [Potato-Development/notepad-sharp#4]
Immediately upon running setup.exe, I get this error box:

![image](https://github.com/Potato-Development/notepad-sharp/assets/76215428/195ec521-ec90-4558-85b6-dfad49c7d538)

When clicking 'details', it gives me this text:

PLATFORM VERSION INFO
	Windows 			: 10.0.22631.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.9176.0 built by: NET481REL1LAST_B
	clr.dll 			: 4.8.9232.0 built by: NET481REL1LAST_C
	dfdll.dll 			: 4.8.9176.0 built by: NET481REL1LAST_B
	dfshim.dll 			: 10.0.22621.30000 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/user/Downloads/notepad-sharp-addedToolbar/notepad%23/notepad%23.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\user\Downloads\notepad-sharp-addedToolbar\notepad#\notepad#.application resulted in exception. Following failure messages were detected:
		+ Exception reading manifest from file:///C:/Users/user/Downloads/notepad-sharp-addedToolbar/notepad%23/notepad%23.application: the manifest may not be valid or the file could not be opened.
		+ Deployment manifest is not semantically valid.
		+ Manifest identity has one or more invalid characters: notepad#.application.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [02/05/2024 14:25:20] : Activation of C:\Users\user\Downloads\notepad-sharp-addedToolbar\notepad#\notepad#.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [02/05/2024 14:25:21] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from file:///C:/Users/user/Downloads/notepad-sharp-addedToolbar/notepad%23/notepad%23.application: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (ManifestSemanticValidation)
		- Deployment manifest is not semantically valid.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSemanticsForDeploymentRole()
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (ManifestComponentSemanticValidation)
		- Manifest identity has one or more invalid characters: notepad#.application.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateAssemblyIdentity(DefinitionIdentity identity)
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSemanticsForDeploymentRole()

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by so1maru** [comment]
Thank you for the error message, the issue is being resolved now.

**Comment by so1maru** [comment]
Installer tested in English and now working
